apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: estate
  labels:
    app: backend
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    nodePort: 30000
    name: http
  selector:
    app: backend
