apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: estate
type: Opaque
stringData:
  DB_USER: estate_user
  DB_PASSWORD: estate_password
  DB_ROOT_PASSWORD: root
  DB_NAME: estateflow
