CREATE DATABASE IF NOT EXISTS estateflow;
USE estateflow;

CREATE TABLE IF NOT EXISTS users(
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100),
  email VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS properties(
  id INT PRIMARY KEY,
  name VARCHAR(100),
  price BIGINT,
  city VARCHAR(100),
  category VARCHAR(50),
  beds INT,
  baths INT,
  area INT,
  image VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS bookmarks(
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT,
  property_id INT
);

CREATE TABLE IF NOT EXISTS contacts(
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT,
  property_id INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS purchases(
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT,
  property_id INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
